interactions:
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python/3.5.2 (Windows-10-10.0.15063-SP0) azure.datalake.store.lib/0.0.10
          Azure-Data-Lake-Store-SDK-For-Python]
      x-ms-client-request-id: [09c7095e-4267-11e7-97f2-645106422854]
    method: GET
    uri: https://fakestore.azuredatalakestore.net/webhdfs/v1/.?OP=GETCONTENTSUMMARY&api-version=2016-11-01
  response:
    body: {string: !!python/unicode '{"ContentSummary":{"directoryCount":5,"fileCount":0,"length":0,"quota":-1,"spaceConsumed":0,"spaceQuota":-1}}'}
    headers:
      Cache-Control: ['no-cache, no-cache, no-store, max-age=0']
      Content-Length: ['109']
      Content-Type: [application/json; charset=utf-8]
      Date: ['Fri, 26 May 2017 22:59:57 GMT']
      Expires: ['-1']
      Pragma: [no-cache]
      Status: ['0x0']
      Strict-Transport-Security: [max-age=15724800; includeSubDomains]
      X-Content-Type-Options: [nosniff]
      x-ms-request-id: [9757aab8-3e3d-4e87-8c97-42f681280194]
      x-ms-webhdfs-version: [16.12.19.00]
    status: {code: 200, message: OK}
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python/3.7.0 (Windows-10-10.0.14393-SP0) azure.datalake.store.lib/0.0.34
          Azure-Data-Lake-Store-SDK-For-Python]
      x-ms-client-request-id: [addd32a6-d190-11e8-8e0b-000d3a041d7c.0]
    method: GET
    uri: https://e2etest160803264425.caboaccountdogfood.net/webhdfs/v1/.?OP=GETCONTENTSUMMARY&api-version=2018-05-01
  response:
    body: {string: !!python/unicode '{"RemoteException":{"exception":"RuntimeException","message":"GETCONTENTSUMMARY
        failed with error 0x8309ffff (Internal server error.). [253ee36a-22cb-4a27-a5c4-98ae8e245c93][2018-10-16T15:13:17.4842237-07:00]","javaClassName":"java.lang.RuntimeException"}}'}
    headers:
      Cache-Control: ['no-cache, no-cache, no-store, max-age=0']
      Content-Length: ['256']
      Content-Type: [application/json; charset=utf-8]
      Date: ['Tue, 16 Oct 2018 22:13:17 GMT']
      Expires: ['-1']
      Pragma: [no-cache]
      Server-Perf: ['[253ee36a-22cb-4a27-a5c4-98ae8e245c93][ AuthTime::0::PostAuthTime::0
          ][S-HdfsGetFileStatus :: 00:00:058 ms]%0a[S-FsEnumerateDirectory :: 00:00:215
          ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory ::
          00:00:019 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:019 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:019 ms]%0a[S-HdfsGetFileStatus :: 00:00:003 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:019 ms]%0a[GETCONTENTSUMMARY :: 00:01:661 ms]%0a']
      Status: ['0x8309FFFF']
      Strict-Transport-Security: [max-age=15724800; includeSubDomains]
      X-Content-Type-Options: [nosniff]
      x-ms-request-id: [253ee36a-22cb-4a27-a5c4-98ae8e245c93]
      x-ms-webhdfs-version: [17.04.24.00]
      x-origin-server: [bn4sch103190535]
    status: {code: 500, message: Internal Server Error}
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python/3.7.0 (Windows-10-10.0.14393-SP0) azure.datalake.store.lib/0.0.34
          Azure-Data-Lake-Store-SDK-For-Python]
      x-ms-client-request-id: [addd32a6-d190-11e8-8e0b-000d3a041d7c.1]
    method: GET
    uri: https://e2etest160803264425.caboaccountdogfood.net/webhdfs/v1/.?OP=GETCONTENTSUMMARY&api-version=2018-05-01
  response:
    body: {string: !!python/unicode '{"RemoteException":{"exception":"RuntimeException","message":"GETCONTENTSUMMARY
        failed with error 0x8309ffff (Internal server error.). [63dc97d3-c7d6-4bb8-a8ab-0f9a57355cd7][2018-10-16T15:13:19.8435683-07:00]","javaClassName":"java.lang.RuntimeException"}}'}
    headers:
      Cache-Control: ['no-cache, no-cache, no-store, max-age=0']
      Content-Length: ['256']
      Content-Type: [application/json; charset=utf-8]
      Date: ['Tue, 16 Oct 2018 22:13:19 GMT']
      Expires: ['-1']
      Pragma: [no-cache]
      Server-Perf: ['[63dc97d3-c7d6-4bb8-a8ab-0f9a57355cd7][ AuthTime::0::PostAuthTime::0
          ][S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory :: 00:00:018
          ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory ::
          00:00:019 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:018 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:018 ms]%0a[S-HdfsGetFileStatus :: 00:00:005 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:019 ms]%0a[GETCONTENTSUMMARY :: 00:01:346 ms]%0a']
      Status: ['0x8309FFFF']
      Strict-Transport-Security: [max-age=15724800; includeSubDomains]
      X-Content-Type-Options: [nosniff]
      x-ms-request-id: [63dc97d3-c7d6-4bb8-a8ab-0f9a57355cd7]
      x-ms-webhdfs-version: [17.04.24.00]
      x-origin-server: [bn4sch103190535]
    status: {code: 500, message: Internal Server Error}
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python/3.7.0 (Windows-10-10.0.14393-SP0) azure.datalake.store.lib/0.0.34
          Azure-Data-Lake-Store-SDK-For-Python]
      x-ms-client-request-id: [addd32a6-d190-11e8-8e0b-000d3a041d7c.2]
    method: GET
    uri: https://e2etest160803264425.caboaccountdogfood.net/webhdfs/v1/.?OP=GETCONTENTSUMMARY&api-version=2018-05-01
  response:
    body: {string: !!python/unicode '{"RemoteException":{"exception":"RuntimeException","message":"GETCONTENTSUMMARY
        failed with error 0x8309ffff (Internal server error.). [a65ab706-c1a0-4f2b-acd3-eaed58d4ec5d][2018-10-16T15:13:25.2028937-07:00]","javaClassName":"java.lang.RuntimeException"}}'}
    headers:
      Cache-Control: ['no-cache, no-cache, no-store, max-age=0']
      Content-Length: ['256']
      Content-Type: [application/json; charset=utf-8]
      Date: ['Tue, 16 Oct 2018 22:13:25 GMT']
      Expires: ['-1']
      Pragma: [no-cache]
      Server-Perf: ['[a65ab706-c1a0-4f2b-acd3-eaed58d4ec5d][ AuthTime::0::PostAuthTime::0
          ][S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory :: 00:00:019
          ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory ::
          00:00:019 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:018 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:019 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:018 ms]%0a[GETCONTENTSUMMARY :: 00:01:343 ms]%0a']
      Status: ['0x8309FFFF']
      Strict-Transport-Security: [max-age=15724800; includeSubDomains]
      X-Content-Type-Options: [nosniff]
      x-ms-request-id: [a65ab706-c1a0-4f2b-acd3-eaed58d4ec5d]
      x-ms-webhdfs-version: [17.04.24.00]
      x-origin-server: [bn4sch103190535]
    status: {code: 500, message: Internal Server Error}
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python/3.7.0 (Windows-10-10.0.14393-SP0) azure.datalake.store.lib/0.0.34
          Azure-Data-Lake-Store-SDK-For-Python]
      x-ms-client-request-id: [addd32a6-d190-11e8-8e0b-000d3a041d7c.3]
    method: GET
    uri: https://e2etest160803264425.caboaccountdogfood.net/webhdfs/v1/.?OP=GETCONTENTSUMMARY&api-version=2018-05-01
  response:
    body: {string: !!python/unicode '{"RemoteException":{"exception":"RuntimeException","message":"GETCONTENTSUMMARY
        failed with error 0x8309ffff (Internal server error.). [528e24df-5bd9-4a8f-9929-537b4e8f3216][2018-10-16T15:13:42.5620672-07:00]","javaClassName":"java.lang.RuntimeException"}}'}
    headers:
      Cache-Control: ['no-cache, no-cache, no-store, max-age=0']
      Content-Length: ['256']
      Content-Type: [application/json; charset=utf-8]
      Date: ['Tue, 16 Oct 2018 22:13:42 GMT']
      Expires: ['-1']
      Pragma: [no-cache]
      Server-Perf: ['[528e24df-5bd9-4a8f-9929-537b4e8f3216][ AuthTime::0::PostAuthTime::0
          ][S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory :: 00:00:020
          ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory ::
          00:00:018 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:018 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:019 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:020 ms]%0a[GETCONTENTSUMMARY :: 00:01:341 ms]%0a']
      Status: ['0x8309FFFF']
      Strict-Transport-Security: [max-age=15724800; includeSubDomains]
      X-Content-Type-Options: [nosniff]
      x-ms-request-id: [528e24df-5bd9-4a8f-9929-537b4e8f3216]
      x-ms-webhdfs-version: [17.04.24.00]
      x-origin-server: [bn4sch103190535]
    status: {code: 500, message: Internal Server Error}
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python/3.7.0 (Windows-10-10.0.14393-SP0) azure.datalake.store.lib/0.0.34
          Azure-Data-Lake-Store-SDK-For-Python]
      x-ms-client-request-id: [addd32a6-d190-11e8-8e0b-000d3a041d7c.4]
    method: GET
    uri: https://e2etest160803264425.caboaccountdogfood.net/webhdfs/v1/.?OP=GETCONTENTSUMMARY&api-version=2018-05-01
  response:
    body: {string: !!python/unicode '{"RemoteException":{"exception":"RuntimeException","message":"GETCONTENTSUMMARY
        failed with error 0x8309ffff (Internal server error.). [681e0560-92ac-4d5c-a407-83609af4b29e][2018-10-16T15:14:48.1081957-07:00]","javaClassName":"java.lang.RuntimeException"}}'}
    headers:
      Cache-Control: ['no-cache, no-cache, no-store, max-age=0']
      Content-Length: ['256']
      Content-Type: [application/json; charset=utf-8]
      Date: ['Tue, 16 Oct 2018 22:14:47 GMT']
      Expires: ['-1']
      Pragma: [no-cache]
      Server-Perf: ['[681e0560-92ac-4d5c-a407-83609af4b29e][ AuthTime::12637.9799761431::PostAuthTime::33977.0010919071
          ][S-HdfsGetFileStatus :: 00:00:026 ms]%0a[S-FsEnumerateDirectory :: 00:00:059
          ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory ::
          00:00:019 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:019 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:020 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:019 ms]%0a[GETCONTENTSUMMARY :: 00:01:394 ms]%0a']
      Status: ['0x8309FFFF']
      Strict-Transport-Security: [max-age=15724800; includeSubDomains]
      X-Content-Type-Options: [nosniff]
      x-ms-request-id: [681e0560-92ac-4d5c-a407-83609af4b29e]
      x-ms-webhdfs-version: [17.04.24.00]
      x-origin-server: [bn4sch103190535]
    status: {code: 500, message: Internal Server Error}
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python/3.7.0 (Windows-10-10.0.14393-SP0) azure.datalake.store.lib/0.0.34
          Azure-Data-Lake-Store-SDK-For-Python]
      x-ms-client-request-id: [f9ac1af4-d190-11e8-ba5e-000d3a041d7c.0]
    method: GET
    uri: https://e2etest160803264425.caboaccountdogfood.net/webhdfs/v1/.?OP=GETCONTENTSUMMARY&api-version=2018-05-01
  response:
    body: {string: !!python/unicode '{"RemoteException":{"exception":"RuntimeException","message":"GETCONTENTSUMMARY
        failed with error 0x8309ffff (Internal server error.). [7057b326-00c1-416e-915c-65dfbaaafd86][2018-10-16T15:15:24.3734112-07:00]","javaClassName":"java.lang.RuntimeException"}}'}
    headers:
      Cache-Control: ['no-cache, no-cache, no-store, max-age=0']
      Content-Length: ['256']
      Content-Type: [application/json; charset=utf-8]
      Date: ['Tue, 16 Oct 2018 22:15:23 GMT']
      Expires: ['-1']
      Pragma: [no-cache]
      Server-Perf: ['[7057b326-00c1-416e-915c-65dfbaaafd86][ AuthTime::0::PostAuthTime::0
          ][S-HdfsGetFileStatus :: 00:00:024 ms]%0a[S-FsEnumerateDirectory :: 00:00:027
          ms]%0a[S-HdfsGetFileStatus :: 00:00:003 ms]%0a[S-FsEnumerateDirectory ::
          00:00:038 ms]%0a[S-HdfsGetFileStatus :: 00:00:003 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:019 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:038 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:019 ms]%0a[GETCONTENTSUMMARY :: 00:01:396 ms]%0a']
      Status: ['0x8309FFFF']
      Strict-Transport-Security: [max-age=15724800; includeSubDomains]
      X-Content-Type-Options: [nosniff]
      x-ms-request-id: [7057b326-00c1-416e-915c-65dfbaaafd86]
      x-ms-webhdfs-version: [17.04.24.00]
      x-origin-server: [bn4sch103190535]
    status: {code: 500, message: Internal Server Error}
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python/3.7.0 (Windows-10-10.0.14393-SP0) azure.datalake.store.lib/0.0.34
          Azure-Data-Lake-Store-SDK-For-Python]
      x-ms-client-request-id: [f9ac1af4-d190-11e8-ba5e-000d3a041d7c.1]
    method: GET
    uri: https://e2etest160803264425.caboaccountdogfood.net/webhdfs/v1/.?OP=GETCONTENTSUMMARY&api-version=2018-05-01
  response:
    body: {string: !!python/unicode '{"RemoteException":{"exception":"RuntimeException","message":"GETCONTENTSUMMARY
        failed with error 0x8309ffff (Internal server error.). [105213cf-6343-4da7-849e-57bd4f483294][2018-10-16T15:15:26.7327652-07:00]","javaClassName":"java.lang.RuntimeException"}}'}
    headers:
      Cache-Control: ['no-cache, no-cache, no-store, max-age=0']
      Content-Length: ['256']
      Content-Type: [application/json; charset=utf-8]
      Date: ['Tue, 16 Oct 2018 22:15:26 GMT']
      Expires: ['-1']
      Pragma: [no-cache]
      Server-Perf: ['[105213cf-6343-4da7-849e-57bd4f483294][ AuthTime::0::PostAuthTime::0
          ][S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory :: 00:00:023
          ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory ::
          00:00:020 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:021 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:022 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:020 ms]%0a[GETCONTENTSUMMARY :: 00:01:342 ms]%0a']
      Status: ['0x8309FFFF']
      Strict-Transport-Security: [max-age=15724800; includeSubDomains]
      X-Content-Type-Options: [nosniff]
      x-ms-request-id: [105213cf-6343-4da7-849e-57bd4f483294]
      x-ms-webhdfs-version: [17.04.24.00]
      x-origin-server: [bn4sch103190535]
    status: {code: 500, message: Internal Server Error}
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python/3.7.0 (Windows-10-10.0.14393-SP0) azure.datalake.store.lib/0.0.34
          Azure-Data-Lake-Store-SDK-For-Python]
      x-ms-client-request-id: [f9ac1af4-d190-11e8-ba5e-000d3a041d7c.2]
    method: GET
    uri: https://e2etest160803264425.caboaccountdogfood.net/webhdfs/v1/.?OP=GETCONTENTSUMMARY&api-version=2018-05-01
  response:
    body: {string: !!python/unicode '{"RemoteException":{"exception":"RuntimeException","message":"GETCONTENTSUMMARY
        failed with error 0x8309ffff (Internal server error.). [57ef17dc-c62e-4e59-bde4-488122d712cc][2018-10-16T15:15:32.0920722-07:00]","javaClassName":"java.lang.RuntimeException"}}'}
    headers:
      Cache-Control: ['no-cache, no-cache, no-store, max-age=0']
      Content-Length: ['256']
      Content-Type: [application/json; charset=utf-8]
      Date: ['Tue, 16 Oct 2018 22:15:32 GMT']
      Expires: ['-1']
      Pragma: [no-cache]
      Server-Perf: ['[57ef17dc-c62e-4e59-bde4-488122d712cc][ AuthTime::0::PostAuthTime::0
          ][S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory :: 00:00:021
          ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory ::
          00:00:020 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:020 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:020 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:020 ms]%0a[GETCONTENTSUMMARY :: 00:01:343 ms]%0a']
      Status: ['0x8309FFFF']
      Strict-Transport-Security: [max-age=15724800; includeSubDomains]
      X-Content-Type-Options: [nosniff]
      x-ms-request-id: [57ef17dc-c62e-4e59-bde4-488122d712cc]
      x-ms-webhdfs-version: [17.04.24.00]
      x-origin-server: [bn4sch103190535]
    status: {code: 500, message: Internal Server Error}
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python/3.7.0 (Windows-10-10.0.14393-SP0) azure.datalake.store.lib/0.0.34
          Azure-Data-Lake-Store-SDK-For-Python]
      x-ms-client-request-id: [f9ac1af4-d190-11e8-ba5e-000d3a041d7c.3]
    method: GET
    uri: https://e2etest160803264425.caboaccountdogfood.net/webhdfs/v1/.?OP=GETCONTENTSUMMARY&api-version=2018-05-01
  response:
    body: {string: !!python/unicode '{"RemoteException":{"exception":"RuntimeException","message":"GETCONTENTSUMMARY
        failed with error 0x8309ffff (Internal server error.). [376edc8a-6d8a-45f5-a1b1-2cd1cbce1a7d][2018-10-16T15:15:49.4512638-07:00]","javaClassName":"java.lang.RuntimeException"}}'}
    headers:
      Cache-Control: ['no-cache, no-cache, no-store, max-age=0']
      Content-Length: ['256']
      Content-Type: [application/json; charset=utf-8]
      Date: ['Tue, 16 Oct 2018 22:15:49 GMT']
      Expires: ['-1']
      Pragma: [no-cache]
      Server-Perf: ['[376edc8a-6d8a-45f5-a1b1-2cd1cbce1a7d][ AuthTime::0::PostAuthTime::0
          ][S-HdfsGetFileStatus :: 00:00:003 ms]%0a[S-FsEnumerateDirectory :: 00:00:020
          ms]%0a[S-HdfsGetFileStatus :: 00:00:005 ms]%0a[S-FsEnumerateDirectory ::
          00:00:020 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:020 ms]%0a[S-HdfsGetFileStatus :: 00:00:003 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:019 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:020 ms]%0a[GETCONTENTSUMMARY :: 00:01:343 ms]%0a']
      Status: ['0x8309FFFF']
      Strict-Transport-Security: [max-age=15724800; includeSubDomains]
      X-Content-Type-Options: [nosniff]
      x-ms-request-id: [376edc8a-6d8a-45f5-a1b1-2cd1cbce1a7d]
      x-ms-webhdfs-version: [17.04.24.00]
      x-origin-server: [bn4sch103190535]
    status: {code: 500, message: Internal Server Error}
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python/3.7.0 (Windows-10-10.0.14393-SP0) azure.datalake.store.lib/0.0.34
          Azure-Data-Lake-Store-SDK-For-Python]
      x-ms-client-request-id: [f9ac1af4-d190-11e8-ba5e-000d3a041d7c.4]
    method: GET
    uri: https://e2etest160803264425.caboaccountdogfood.net/webhdfs/v1/.?OP=GETCONTENTSUMMARY&api-version=2018-05-01
  response:
    body: {string: !!python/unicode '{"RemoteException":{"exception":"RuntimeException","message":"GETCONTENTSUMMARY
        failed with error 0x8309ffff (Internal server error.). [dfdc9051-016a-48ee-b0db-94dc67c5b142][2018-10-16T15:16:54.8567746-07:00]","javaClassName":"java.lang.RuntimeException"}}'}
    headers:
      Cache-Control: ['no-cache, no-cache, no-store, max-age=0']
      Content-Length: ['256']
      Content-Type: [application/json; charset=utf-8]
      Date: ['Tue, 16 Oct 2018 22:16:54 GMT']
      Expires: ['-1']
      Pragma: [no-cache]
      Server-Perf: ['[dfdc9051-016a-48ee-b0db-94dc67c5b142][ AuthTime::921.684214308046::PostAuthTime::745.045893886133
          ][S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory :: 00:00:019
          ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory ::
          00:00:020 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:019 ms]%0a[S-HdfsGetFileStatus :: 00:00:004 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:023 ms]%0a[S-HdfsGetFileStatus :: 00:00:003 ms]%0a[S-FsEnumerateDirectory
          :: 00:00:018 ms]%0a[GETCONTENTSUMMARY :: 00:01:336 ms]%0a']
      Status: ['0x8309FFFF']
      Strict-Transport-Security: [max-age=15724800; includeSubDomains]
      X-Content-Type-Options: [nosniff]
      x-ms-request-id: [dfdc9051-016a-48ee-b0db-94dc67c5b142]
      x-ms-webhdfs-version: [17.04.24.00]
      x-origin-server: [bn4sch103190535]
    status: {code: 500, message: Internal Server Error}
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python/3.7.0 (Windows-10-10.0.14393-SP0) azure.datalake.store.lib/0.0.34
          Azure-Data-Lake-Store-SDK-For-Python]
      x-ms-client-request-id: [ba580fe2-d194-11e8-8468-000d3a041d7c.0]
    method: GET
    uri: https://akharitadls.azuredatalakestore.net/webhdfs/v1/.?OP=GETCONTENTSUMMARY&api-version=2018-05-01
  response:
    body: {string: !!python/unicode '{"ContentSummary":{"directoryCount":4,"fileCount":0,"length":0,"quota":-1,"spaceConsumed":0,"spaceQuota":-1}}'}
    headers:
      Cache-Control: ['no-cache, no-cache, no-store, max-age=0']
      Content-Length: ['109']
      Content-Type: [application/json; charset=utf-8]
      Date: ['Tue, 16 Oct 2018 22:42:13 GMT']
      Expires: ['-1']
      Pragma: [no-cache]
      Status: ['0x0']
      Strict-Transport-Security: [max-age=15724800; includeSubDomains]
      X-Content-Type-Options: [nosniff]
      x-ms-request-id: [79ea5aa4-6554-4650-90f4-6bf7d6a00096]
      x-ms-webhdfs-version: [17.04.24.00]
    status: {code: 200, message: OK}
- request:
    body: null
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      User-Agent: [python/2.7.13 (Windows-10-10.0.14393) azure.datalake.store.lib/0.0.34
          Azure-Data-Lake-Store-SDK-For-Python]
      x-ms-client-request-id: [54ffba8f-dbd6-11e8-8c6a-000d3a041d7c.0]
    method: GET
    uri: https://akharitadls.azuredatalakestore.net/webhdfs/v1/.?api-version=2018-05-01&OP=GETCONTENTSUMMARY
  response:
    body: {string: !!python/unicode '{"ContentSummary":{"directoryCount":102,"fileCount":30,"length":180,"quota":-1,"spaceConsumed":180,"spaceQuota":-1}}'}
    headers:
      cache-control: ['no-cache, no-cache, no-store, max-age=0']
      content-length: ['116']
      content-type: [application/json; charset=utf-8]
      date: ['Mon, 29 Oct 2018 23:57:04 GMT']
      expires: ['-1']
      pragma: [no-cache]
      status: ['0x0']
      strict-transport-security: [max-age=15724800; includeSubDomains]
      x-content-type-options: [nosniff]
      x-ms-request-id: [176dccc5-12ab-4165-9d1d-b5e90e8df9f6]
      x-ms-webhdfs-version: [17.04.24.00]
    status: {code: 200, message: OK}
version: 1
